#ifndef COMPONENTS_MQTT5_CONNECTION_INCLUDE_MQTT5_CONNECTION
#define COMPONENTS_MQTT5_CONNECTION_INCLUDE_MQTT5_CONNECTION

#define CONFIG_BROKER_URL "brocker_url"

void mqtt5_conn_init(void);

#endif /* COMPONENTS_MQTT5_CONNECTION_INCLUDE_MQTT5_CONNECTION */
