name: pre_commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install -y clang-tidy clang-format cppcheck
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --show-diff-on-failure --all-files
