name: pre_commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set lower case repository name
        run: |
          echo "REPOSITORY_LC=${REPOSITORYNAME,,}" >>${GITHUB_ENV}
        env:
          REPOSITORYNAME: "${{ github.repository }}"
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          imageName: ghcr.io/${{ github.repository_owner }}/ebbflowcontrol-devcontainer
          # Change this to be your CI task/script
          runCmd: |
            pre-commit run --show-diff-on-failure --all-files
